# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

config:
  line-length: false
  link-fragments: false
  list-marker-space: false # https://github.com/prettier/prettier/issues/5019
  no-alt-text: false
  no-bare-urls: false
  no-inline-html: false
  no-trailing-punctuation: false
  ul-indent:
    indent: 4
gitignore: true
