# https://yamllint.readthedocs.io/en/stable/rules.html

extends: default
ignore-from-file: .gitignore
rules:
  comments:
    min-spaces-from-content: 1
  document-start:
    present: false
  line-length: false
  truthy:
    check-keys: false
