site_name: hogent-mkdocs
site_url: https://hogent.be
copyright: Copyright &copy; HOGENT (<a href="https://hogent.be">https://hogent.be</a>)
nav:
    - Home: ./index.md
    - Basic examples: ./examples/h1.md
    - Advanced examples: ./examples/h2.md
    - Links: ./links.md
theme:
    name: material # https://squidfunk.github.io/mkdocs-material/setup/
    favicon: https://hogent.be/themes/hogent/images/ico/favicon.ico
    features:
        - content.code.copy
        - navigation.path
        - navigation.top
        - navigation.tracking
        - toc.integrate
        - toc.follow
    font:
        text: Montserrat
        code: Inconsolata
    logo: https://www.hogent.be/sites/hogent/assets/Image/logo-1.jpg
markdown_extensions:
    - footnotes
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.caret
    - pymdownx.emoji
    - pymdownx.highlight:
          anchor_linenums: true
          auto_title: true
          linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.saneheaders
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist
    - pymdownx.tilde
    - toc:
          permalink: true
plugins:
    - git-revision-date-localized:
          fallback_to_build_date: true
          type: datetime
    - plantuml:
          puml_url: https://www.plantuml.com/plantuml/
          num_workers: 8
    - search
extra_javascript:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
